### ISSUE TITLE
Generate Class from JSON with array as root

### ISSUE THREAD

**Issue by compubinkie** [PKGeorgiev/Delphi-JsonToDelphiClass#4]
Hi Petar,

What a great tool!!!

Could you verify the following behavior. The tool does not seem to be able to cope with a JSON string with an array as root (jsonlint reports the string to be valid JSON):

```
    [
    {
      "Id":"9165d168-c6de-4eea-b280-1fc147576199",
      "Description":"Your Advice",
      "Code":"NL_YR_ADV"
    },
    {
      "Id":"d03a1dbf-5b3f-4dd4-ba07-0ffd3b67ca6f",
      "Description":"Your Garden Products",
      "Code":"NL_YR_GRD"
    }
  ]
```

The tool still generates a correct ItemClass, but the TRootClass.FromJsonString assumes the JSON "root" to be an object, which in the end (when using calling TRootClass.FromJsonString) generates an error "input value is not a valid Object" and/or Access Violation, because in this case the "root" is an array.

Please, could you ...
1) explain whether this is by design
2) change the tool so it will generate a correct TRootClass.FromJsonString
3) tell me what would be the most decent work around, if it cannot be changed in the tool.

Regards,
Erik

**Comment by PKGeorgiev** [comment]
Hi Erik,

Do you mean you want your sample JSON to be represented as ```TArray<itemType>``` where itemType represents array's element type?

Regards

**Comment by compubinkie** [comment]
Hi Petar,
I cannot remember why I asked this question (to be honest, I hardly remember asking the question at all), but after re-reading the question I think your interpretation is correct.
Regards,
Erik

**Comment by PKGeorgiev** [comment]
@compubinkie generating a class instead of just TArray<SomeType> is more flexible, because you can later extend the class and take advantage of ToJsonString/FromJsonString functions etc. As far as I know it is more popular for the web services to return objects with collections inside - something like { results: [{obj1},{obj2}] } (for example ExtJs) instead of directly returning plain arrays.
Also currently Rest.TJson (which is used for the actual conversion) does not offer a way to convert a JSON string that represents arrays to be directly converted to TArray. I'll think about it in the future.

In your case you can use Delphi2JsonClass to generate a class for Array's elements:

```js
    {
      "Id":"d03a1dbf-5b3f-4dd4-ba07-0ffd3b67ca6f",
      "Description":"Your Garden Products",
      "Code":"NL_YR_GRD"
    }
```

Then use low level Json functions to represent it as array. Pseudo code:

```pascal
procedure test;
var
LJsonArr   : TJSONArray;
begin
  LJsonArr    := TJSONObject.ParseJSONValue(TEncoding.ASCII.GetBytes(StrJson),0) as TJSONArray;
  for LJsonValue in LJsonArr do
  begin
    // Process array items here
  end
end;
```

Other example: https://stackoverflow.com/a/14867175

**Comment by compubinkie** [comment]
Hi Petar,

I totally agree a class is more flexible.

The thing is, that our software interfaces to a web service (If I remember correctly, it is the web service that is part of Dutch accounting software called AccountView, https://nl.visma.com/producten/accountview/) that returns these types of array JSON strings.

I know we already have a solution for handling these array JSON strings, possibly similar to your suggestion.

Thanks anyway for your help.
